# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/
#
# IMPORTANT: This site has SSR capabilities via Express server (server.js)
# but Netlify is a static host that doesn't run Node servers.
#
# Build Strategy:
# - Local dev: npm run dev (Vite dev server, no SSR)
# - SSR preview: node server.js (Express with SSR for SEO testing)
# - Netlify deploy: npm run build:client (static build only)
#
# SSR manifest is generated (vite.config.ts: ssrManifest: true) but only
# used when running server.js locally. Netlify serves static files from dist/client.

[build]
  publish = "dist/client"
  command = "npm run build:client"

# SPA fallback - serve index.html for client-side routing
# Static files (including /2024-legacy/*) are served first by Netlify
# This rule only applies when no static file exists
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Font caching - immutable for performance
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files - ensure correct MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Image caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Legacy site image caching
[[headers]]
  for = "/2024-legacy/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML - no cache for updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Legacy site HTML - no cache
[[headers]]
  for = "/2024-legacy/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
