# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  command = "npm run build"

# Legacy site redirect rules
# Serve the 2024 legacy photography portfolio at /2024-legacy/
[[redirects]]
  from = "/2024-legacy/*"
  to = "/2024-legacy/:splat"
  status = 200
  force = false

# Font caching - immutable for performance
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Legacy site image caching
[[headers]]
  for = "/2024-legacy/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML - no cache for updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Legacy site HTML - no cache
[[headers]]
  for = "/2024-legacy/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
