# Netlify Configuration
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  publish = "dist"
  command = "npm run build"

# SPA fallback - serve index.html for client-side routing
# Static files (including /2024-legacy/*) are served first by Netlify
# This rule only applies when no static file exists
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Font caching - immutable for performance
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Asset caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files - ensure correct MIME type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Image caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Legacy site image caching
[[headers]]
  for = "/2024-legacy/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML - no cache for updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Legacy site HTML - no cache
[[headers]]
  for = "/2024-legacy/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
